### ISSUE TITLE
Does this driver support the MPG interface?

### ISSUE THREAD

**Issue by kizmit99** [grblHAL/SAMD21#3]
First off - sorry for entering this as "an issue", but this repo doesn't appear to have discussions enabled?

Anyway - I'm in the process of designing a pendant to use with my grblHAL (Teensy 4.1) based CNC mill.  I'm putting together a test bench and I was hoping to use a MKRZero board as a stand-in for the mill,  I have been able to work around the 'synchronized' compile issue and have an instance of ioSender talking to the MKRZero.  

When I edit my_machine.h I do not find the #defines for KEYBOARD_ENABLE, MPG_ENABLE and I2C_STROBE_ENABLE (as I do in the Teensy4 driver's my_machine.h).  I can define KEYBOARD_ENABLE and MPG_ENABLE (as 2) and get everything compiled, but I suspect that may not be enough to actually enable the MPG interface (at least the external serial port on the MKRZero doesn't seem to be active).

Am I missing something, or is it possible that the MPG interface is not actually implemented for this driver?
Thanks in advance!

**Comment by terjeio** [comment]
Keypad and MPG mode is not implemented and has to be added to driver.c.
Are you willing to do it? You can use the [iMXRT1062 driver code](https://github.com/grblHAL/iMXRT1062/blob/master/grblHAL_Teensy4/src/driver.c) as an example, search for KEYPAD_ENABLE and MPG_MODE to find the parts that has to be added.

**Comment by kizmit99** [comment]
I will take a look at porting it over...

**Comment by kizmit99** [comment]
In the end I just purchased another Teensy to do my development against.  Closing this.
